# Generated by Django 5.2.17 on 2026-09-19 12:29

import careers.models
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Project Management", "Project Management"),
                            ("Architecture Studio", "Architecture Studio"),
                            ("Administration", "Administration"),
                        ],
                        max_length=60,
                    ),
                ),
                ("location", models.CharField(max_length=120)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                        ],
                        default="Full-time",
                        max_length=40,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '3-5 years'. Optional.",
                        max_length=80,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="One per line. Each line becomes a bullet point.",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="One per line. Each line becomes a bullet point.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "-posted_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "sort_order"],
                        name="careers_job_status_89fbe7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title_snapshot", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        storage=careers.models.PrivateStorage(
                            location=pathlib.PureWindowsPath(
                                "C:/Users/abhis/Documents/Abhishek_Documents/websites/admireartitects/backend/private_media"
                            )
                        ),
                        upload_to="resumes/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="careers.jobopening",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="careers_job_created_6c06be_idx"
                    )
                ],
            },
        ),
    ]
