# Generated by Django 5.2.17 on 2026-09-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="coa_registration",
            field=models.CharField(
                blank=True,
                help_text="Council of Architecture number, for registered architects.",
                max_length=60,
                verbose_name="CoA registration no.",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="current_ctc",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="current_designation",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="current_employer",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="current_location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="expected_ctc",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="graduation_year",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="highest_qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B.Arch", "B.Arch"),
                    ("M.Arch", "M.Arch"),
                    ("B.E / B.Tech (Civil)", "B.E / B.Tech (Civil)"),
                    ("M.E / M.Tech", "M.E / M.Tech"),
                    ("Diploma in Architecture", "Diploma in Architecture"),
                    ("Interior Design", "Interior Design"),
                    ("Other", "Other"),
                ],
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="institution",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="notice_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Immediately available", "Immediately available"),
                    ("15 days", "15 days"),
                    ("30 days", "30 days"),
                    ("60 days", "60 days"),
                    ("90 days", "90 days"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="open_to_relocation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Depends on the role", "Depends on the role"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="portfolio_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="project_types",
            field=models.TextField(blank=True, help_text="One per line."),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="software_skills",
            field=models.TextField(blank=True, help_text="One per line."),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="years_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-1 years", "0-1 years"),
                    ("1-3 years", "1-3 years"),
                    ("3-5 years", "3-5 years"),
                    ("5-8 years", "5-8 years"),
                    ("8-12 years", "8-12 years"),
                    ("12+ years", "12+ years"),
                ],
                max_length=40,
            ),
        ),
    ]
