# Generated by Django 5.2.17 on 2026-09-19 12:29

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the page URL, e.g. /projects/latestprojects-0. Changing this breaks existing links — leave it alone once saved.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "location",
                    models.CharField(default="Multiple Locations", max_length=120),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Floor area or project value, e.g. '40,000 SFT'. Leave empty to hide the Scale field.",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Latest Projects", "Latest Projects"),
                            ("Design & PMC", "Design & PMC"),
                            ("Turnkey Projects", "Turnkey Projects"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first within the category.",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublish to hide from the website without deleting.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["category", "sort_order"],
                        name="content_pro_categor_a7cd59_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to=content.models._upload_to),
                ),
                (
                    "legacy_path",
                    models.CharField(
                        blank=True,
                        help_text="Site-relative path for original photography, e.g. /Admire Website - Project Images/...",
                        max_length=300,
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["project", "sort_order"],
                        name="content_pro_project_051f90_idx",
                    )
                ],
            },
        ),
    ]
