"""
Load the site's existing projects from backend/seed/projects.json.

    python manage.py import_projects [--reset] [--file PATH]

Generated by `npx tsx scripts/export-projects.ts` on the frontend side. Run
once after the first migrate; it is idempotent, so re-running only refreshes
metadata and image rows rather than duplicating them.

No photographs are uploaded. The original 292MB of project photography stays
committed under the Next.js public/ folder, already served by Vercel's CDN, so
each image row simply records its site-relative path. Only photos added through
the dashboard from now on live on this server's disk.
"""

import json
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from content.models import CATEGORY_ORDER, Project, ProjectImage

DEFAULT_SEED = Path(settings.BASE_DIR) / "seed" / "projects.json"


class Command(BaseCommand):
    help = "Import projects and their photography paths from the seed JSON."

    def add_arguments(self, parser):
        parser.add_argument(
            "--file",
            default=str(DEFAULT_SEED),
            help=f"Seed JSON to read (default: {DEFAULT_SEED})",
        )
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete every existing project first. Destroys dashboard edits.",
        )

    def handle(self, *args, **options):
        path = Path(options["file"])
        if not path.exists():
            raise CommandError(
                f"Seed file not found: {path}\n"
                "Generate it first with:  npx tsx scripts/export-projects.ts"
            )

        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except ValueError as exc:
            raise CommandError(f"Seed file is not valid JSON: {exc}") from exc

        records = payload.get("projects", [])
        if not records:
            raise CommandError("Seed file contains no projects.")

        unknown = {r["category"] for r in records} - set(CATEGORY_ORDER)
        if unknown:
            raise CommandError(
                "Seed contains categories the model does not allow: "
                + ", ".join(sorted(unknown))
            )

        with transaction.atomic():
            if options["reset"]:
                deleted, _ = Project.objects.all().delete()
                self.stdout.write(self.style.WARNING(f"Deleted {deleted} existing row(s)."))

            created = updated = image_count = 0

            for record in records:
                project, was_created = Project.objects.update_or_create(
                    slug=record["slug"],
                    defaults={
                        "title": record["title"],
                        "location": record["location"],
                        "area": record.get("area") or None,
                        "category": record["category"],
                        "description": record["description"],
                        "sort_order": record.get("sortOrder", 0),
                        "published": True,
                    },
                )
                created += was_created
                updated += not was_created

                # Replace only the legacy rows, so photos the client has
                # uploaded through the dashboard survive a re-run.
                project.images.filter(legacy_path__gt="").delete()

                for index, image_path in enumerate(record.get("images", [])):
                    ProjectImage.objects.create(
                        project=project,
                        legacy_path=image_path,
                        alt=f"{record['title']}, {record['location']}",
                        sort_order=index,
                    )
                    image_count += 1

        photo_projects = sum(1 for r in records if r.get("images"))
        distinct_sets = len({r["images"][0] for r in records if r.get("images")})
        distinct_files = len({img for r in records for img in r.get("images", [])})

        self.stdout.write(
            self.style.SUCCESS(
                f"\nImported {len(records)} projects "
                f"({created} created, {updated} updated).\n"
                f"  {image_count} image rows across {photo_projects} projects\n"
                f"  {distinct_sets} distinct photo sets, {distinct_files} distinct files\n"
            )
        )
